/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmoiqRouteImport } from './routes/emoiq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmoiqIndexRouteImport } from './routes/emoiq.index'
import { Route as EmoiqQuizRouteImport } from './routes/emoiq.quiz'
import { Route as EmoiqPredictRouteImport } from './routes/emoiq.predict'
import { Route as EmoiqPlanRouteImport } from './routes/emoiq.plan'
import { Route as EmoiqDoubtRouteImport } from './routes/emoiq.doubt'
import { Route as EmoiqAnalyzeRouteImport } from './routes/emoiq.analyze'

const EmoiqRoute = EmoiqRouteImport.update({
  id: '/emoiq',
  path: '/emoiq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmoiqIndexRoute = EmoiqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqQuizRoute = EmoiqQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqPredictRoute = EmoiqPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqPlanRoute = EmoiqPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqDoubtRoute = EmoiqDoubtRouteImport.update({
  id: '/doubt',
  path: '/doubt',
  getParentRoute: () => EmoiqRoute,
} as any)
const EmoiqAnalyzeRoute = EmoiqAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => EmoiqRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emoiq': typeof EmoiqRouteWithChildren
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/emoiq/': typeof EmoiqIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/emoiq': typeof EmoiqIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/emoiq': typeof EmoiqRouteWithChildren
  '/emoiq/analyze': typeof EmoiqAnalyzeRoute
  '/emoiq/doubt': typeof EmoiqDoubtRoute
  '/emoiq/plan': typeof EmoiqPlanRoute
  '/emoiq/predict': typeof EmoiqPredictRoute
  '/emoiq/quiz': typeof EmoiqQuizRoute
  '/emoiq/': typeof EmoiqIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/emoiq'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/emoiq/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/emoiq'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/emoiq'
    | '/emoiq/analyze'
    | '/emoiq/doubt'
    | '/emoiq/plan'
    | '/emoiq/predict'
    | '/emoiq/quiz'
    | '/emoiq/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EmoiqRoute: typeof EmoiqRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/emoiq': {
      id: '/emoiq'
      path: '/emoiq'
      fullPath: '/emoiq'
      preLoaderRoute: typeof EmoiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoiq/': {
      id: '/emoiq/'
      path: '/'
      fullPath: '/emoiq/'
      preLoaderRoute: typeof EmoiqIndexRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/quiz': {
      id: '/emoiq/quiz'
      path: '/quiz'
      fullPath: '/emoiq/quiz'
      preLoaderRoute: typeof EmoiqQuizRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/predict': {
      id: '/emoiq/predict'
      path: '/predict'
      fullPath: '/emoiq/predict'
      preLoaderRoute: typeof EmoiqPredictRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/plan': {
      id: '/emoiq/plan'
      path: '/plan'
      fullPath: '/emoiq/plan'
      preLoaderRoute: typeof EmoiqPlanRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/doubt': {
      id: '/emoiq/doubt'
      path: '/doubt'
      fullPath: '/emoiq/doubt'
      preLoaderRoute: typeof EmoiqDoubtRouteImport
      parentRoute: typeof EmoiqRoute
    }
    '/emoiq/analyze': {
      id: '/emoiq/analyze'
      path: '/analyze'
      fullPath: '/emoiq/analyze'
      preLoaderRoute: typeof EmoiqAnalyzeRouteImport
      parentRoute: typeof EmoiqRoute
    }
  }
}

interface EmoiqRouteChildren {
  EmoiqAnalyzeRoute: typeof EmoiqAnalyzeRoute
  EmoiqDoubtRoute: typeof EmoiqDoubtRoute
  EmoiqPlanRoute: typeof EmoiqPlanRoute
  EmoiqPredictRoute: typeof EmoiqPredictRoute
  EmoiqQuizRoute: typeof EmoiqQuizRoute
  EmoiqIndexRoute: typeof EmoiqIndexRoute
}

const EmoiqRouteChildren: EmoiqRouteChildren = {
  EmoiqAnalyzeRoute: EmoiqAnalyzeRoute,
  EmoiqDoubtRoute: EmoiqDoubtRoute,
  EmoiqPlanRoute: EmoiqPlanRoute,
  EmoiqPredictRoute: EmoiqPredictRoute,
  EmoiqQuizRoute: EmoiqQuizRoute,
  EmoiqIndexRoute: EmoiqIndexRoute,
}

const EmoiqRouteWithChildren = EmoiqRoute._addFileChildren(EmoiqRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EmoiqRoute: EmoiqRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
